AWSTemplateFormatVersion: 2010-09-09
Description: API de Mythical Mysfits con Auto Scaling Groups.

Mappings:
  RegionMap:
    us-east-1:
      "AmiId": "ami-09d95fab7fff3776c"
    us-east-2:
      "AmiId": "ami-026dea5602e368e96"
    us-west-2:
      "AmiId": "ami-0e34e7b9ca0ace12d"

Resources:
  LoadBalancerSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: MythicalMysfitsLB
      GroupDescription: Load Balancer
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
  InstanceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: MythicalMysfitsInstance
      GroupDescription: Instances
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 8000
        ToPort: 8080
        SourceSecurityGroupName: !Ref LoadBalancerSG
  LoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      Scheme: internet-facing
      SecurityGroups:
        - !GetAtt LoadBalancerSG.GroupId
      AvailabilityZones: !GetAZs
      Listeners:
        - InstancePort: 8000
          InstanceProtocol: tcp
          LoadBalancerPort: 80
          Protocol: tcp
      HealthCheck:
        HealthyThreshold: 2
        Interval: 30
        Target: "TCP:8080"
        Timeout: 5
        UnhealthyThreshold: 5
  LaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !FindInMap
        - RegionMap
        - !Ref AWS::Region
        - AmiId
      InstanceType: t2.micro
      KeyName: mythical-mysfits
      SecurityGroups:
        - !GetAtt InstanceSG.GroupId
      UserData:
        Fn::Base64: | 
          #!/bin/bash 
          yum install -y python37
          curl -O https://bootstrap.pypa.io/get-pip.py
          python3 get-pip.py
          yum install -y git
          git clone https://github.com/mimi-mede/bootcamp-module-devops.git
          cd /bootcamp-module-devops/backend/
          /usr/local/bin/pip install -r requirements.txt
          nohup /usr/local/bin/gunicorn -w 3 -b 0.0.0.0:8080 app:app & 
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones: !GetAZs
      AutoScalingGroupName: MysfitsASG
      MinSize: "1"
      MaxSize: "1"
      DesiredCapacity: "1"
      HealthCheckGracePeriod: 300
      LaunchConfigurationName: !Ref LaunchConfiguration
      LoadBalancerNames: 
        - !Ref LoadBalancer